version: '3'
services:
  aws:
    image: radhika2810/trainingsaws:latest
    ports:
      - "8000:80"
    deploy:
      replicas: 3

  devops:
    image: radhika2810/trainingsdevops:latest
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  azure:
    image: radhika2810/trainingsazure:latest
    ports:
      - "8002:80"
    deploy:
      replicas: 5

  datascience:
    image: radhika2810/trainingsdatascience:latest
    ports:
      - "8003:80"
    deploy:
      replicas: 5
